vich_uploader:
  db_driver: orm
  mappings:
    product_image:
      uri_prefix: /photos/
      upload_destination: '%kernel.project_dir%/public/photos'
      namer:
        service: vich_uploader.namer_origname
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: false
